--.........................................................................
--SQL script for post deployment configuration of load control
--Project: Product Launch Event
--Layer: Stage
--.........................................................................
USE [{loadcontrol#loadcontrol#database_name}];
GO


--.........................................................................
--Prepare registration of load objects
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[Build_LoadConfig] @LoadConfig = N'Product Launch Event', @ModelObjectLayer = N'Stage';

--.........................................................................
--Register load objects
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'BRANCH',                               @ModelObjectPart = N'Stage Loader',                         @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Stage',                                @ModelObjectType = N'Stage',                                @LoadObject = N'STG_ST_BRANCH_Loader',                 @SchemaName = N'{productlaunchevent#stage#schema_name}', @DatabaseName = N'{productlaunchevent#stage#database_name}', @ServerName = N'{productlaunchevent#stage#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 1020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'CUSTOMER',                             @ModelObjectPart = N'Stage Loader',                         @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Stage',                                @ModelObjectType = N'Stage',                                @LoadObject = N'STG_ST_CUSTOMER_Loader',               @SchemaName = N'{productlaunchevent#stage#schema_name}', @DatabaseName = N'{productlaunchevent#stage#database_name}', @ServerName = N'{productlaunchevent#stage#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 1020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'CUSTOMER_DUPLICATES',                  @ModelObjectPart = N'Stage Loader',                         @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Stage',                                @ModelObjectType = N'Stage',                                @LoadObject = N'STG_ST_CUSTOMER_DUPLICATES_Loader',    @SchemaName = N'{productlaunchevent#stage#schema_name}', @DatabaseName = N'{productlaunchevent#stage#database_name}', @ServerName = N'{productlaunchevent#stage#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 1020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'EMPLOYEE',                             @ModelObjectPart = N'Stage Loader',                         @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Stage',                                @ModelObjectType = N'Stage',                                @LoadObject = N'STG_ST_EMPLOYEE_Loader',               @SchemaName = N'{productlaunchevent#stage#schema_name}', @DatabaseName = N'{productlaunchevent#stage#database_name}', @ServerName = N'{productlaunchevent#stage#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 1020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEM',                                 @ModelObjectPart = N'Stage Loader',                         @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Stage',                                @ModelObjectType = N'Stage',                                @LoadObject = N'STG_ST_ITEM_Loader',                   @SchemaName = N'{productlaunchevent#stage#schema_name}', @DatabaseName = N'{productlaunchevent#stage#database_name}', @ServerName = N'{productlaunchevent#stage#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 1020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEMUNITOFMEASURE',                    @ModelObjectPart = N'Stage Loader',                         @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Stage',                                @ModelObjectType = N'Stage',                                @LoadObject = N'STG_ST_ITEMUNITOFMEASURE_Loader',      @SchemaName = N'{productlaunchevent#stage#schema_name}', @DatabaseName = N'{productlaunchevent#stage#database_name}', @ServerName = N'{productlaunchevent#stage#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 1020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'LOYALTYCARD',                          @ModelObjectPart = N'Stage Loader',                         @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Stage',                                @ModelObjectType = N'Stage',                                @LoadObject = N'STG_ST_LOYALTYCARD_Loader',            @SchemaName = N'{productlaunchevent#stage#schema_name}', @DatabaseName = N'{productlaunchevent#stage#database_name}', @ServerName = N'{productlaunchevent#stage#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 1020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'PHONENUMBER',                          @ModelObjectPart = N'Stage Loader',                         @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Stage',                                @ModelObjectType = N'Stage',                                @LoadObject = N'STG_ST_PHONENUMBER_Loader',            @SchemaName = N'{productlaunchevent#stage#schema_name}', @DatabaseName = N'{productlaunchevent#stage#database_name}', @ServerName = N'{productlaunchevent#stage#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 1020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'POS',                                  @ModelObjectPart = N'Stage Loader',                         @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Stage',                                @ModelObjectType = N'Stage',                                @LoadObject = N'STG_ST_POS_Loader',                    @SchemaName = N'{productlaunchevent#stage#schema_name}', @DatabaseName = N'{productlaunchevent#stage#database_name}', @ServerName = N'{productlaunchevent#stage#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 1020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'SALESTRANSACTION',                     @ModelObjectPart = N'Stage Loader',                         @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Stage',                                @ModelObjectType = N'Stage',                                @LoadObject = N'STG_ST_SALESTRANSACTION_Loader',       @SchemaName = N'{productlaunchevent#stage#schema_name}', @DatabaseName = N'{productlaunchevent#stage#database_name}', @ServerName = N'{productlaunchevent#stage#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 1020, @ExecutionPriority = 0, @IsActive = 1;

--.........................................................................
--Register load object dependencies
--.........................................................................


GO
