--.........................................................................
--SQL script for post deployment configuration of load control
--Project: Product Launch Event
--Layer: Raw Vault
--.........................................................................
USE [{loadcontrol#loadcontrol#database_name}];
GO


--.........................................................................
--Prepare registration of load objects
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[Build_LoadConfig] @LoadConfig = N'Product Launch Event', @ModelObjectLayer = N'Raw Vault';

--.........................................................................
--Register load objects
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'BRANCH',                               @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Satellite',                            @LoadObject = N'RDV_SAT_BRANCH_Loader',                @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'CUSTOMER',                             @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_CUSTOMER_Loader',              @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'CUSTOMER_Address',                     @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Satellite',                            @LoadObject = N'RDV_SAT_CUSTOMER_Address_Loader',      @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'CUSTOMER_Info',                        @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Satellite',                            @LoadObject = N'RDV_SAT_CUSTOMER_Info_Loader',         @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'EMPLOYEE',                             @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_EMPLOYEE_Loader',              @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'EMPLOYEE',                             @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Satellite',                            @LoadObject = N'RDV_SAT_EMPLOYEE_Loader',              @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'EMPLOYEE1',                            @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_EMPLOYEE1_Loader',             @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEM',                                 @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_ITEM_Loader',                  @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEM',                                 @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Satellite',                            @LoadObject = N'RDV_SAT_ITEM_Loader',                  @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEMUNITOFMEASURE',                    @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_ITEMUNITOFMEASURE_Loader',     @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEMUNITOFMEASURE',                    @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Satellite',                            @LoadObject = N'RDV_SAT_ITEMUNITOFMEASURE_Loader',     @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'LOYALTYCARD',                          @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_LOYALTYCARD_Loader',           @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Loyaltycard_Customer',                 @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Link',                                 @LoadObject = N'RDV_LNK_Loyaltycard_Customer_Loader',  @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'PHONENUMBER',                          @ModelObjectPart = N'Multi-Active Satellite Loader',        @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Multi-Active Satellite',               @LoadObject = N'RDV_MAS_PHONENUMBER_Loader',           @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'POS',                                  @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_POS_Loader',                   @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'POS_Branch',                           @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Link',                                 @LoadObject = N'RDV_LNK_POS_Branch_Loader',            @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'POS_SALES',                            @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Link',                                 @LoadObject = N'RDV_LNK_POS_SALES_Loader',             @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'SALESTRANSACTION',                     @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Hub',                                  @LoadObject = N'RDV_HUB_SALESTRANSACTION_Loader',      @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'SALESTRANSACTION',                     @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Raw Vault',                            @ModelObjectType = N'Satellite',                            @LoadObject = N'RDV_SAT_SALESTRANSACTION_Loader',      @SchemaName = N'{productlaunchevent#rawvault#schema_name}', @DatabaseName = N'{productlaunchevent#rawvault#database_name}', @ServerName = N'{productlaunchevent#rawvault#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2040, @ExecutionPriority = 0, @IsActive = 1;

--.........................................................................
--Register load object dependencies
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'BRANCH',                               @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'BRANCH',                               @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'CUSTOMER',                             @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'CUSTOMER',                             @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'CUSTOMER_Address',                     @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'CUSTOMER',                             @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'CUSTOMER_Info',                        @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'CUSTOMER',                             @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'EMPLOYEE',                             @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'EMPLOYEE',                             @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'EMPLOYEE',                             @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'EMPLOYEE',                             @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'EMPLOYEE1',                            @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'EMPLOYEE',                             @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEM',                                 @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'ITEM',                                 @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEM',                                 @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'ITEM',                                 @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEMUNITOFMEASURE',                    @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'ITEMUNITOFMEASURE',                    @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEMUNITOFMEASURE',                    @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'ITEMUNITOFMEASURE',                    @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'LOYALTYCARD',                          @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'LOYALTYCARD',                          @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Loyaltycard_Customer',                 @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'LOYALTYCARD',                          @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'PHONENUMBER',                          @ModelObjectPart = N'Multi-Active Satellite Loader',        @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'PHONENUMBER',                          @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'POS',                                  @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'POS_Branch',                           @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'POS_SALES',                            @ModelObjectPart = N'Link Loader',                          @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'SALESTRANSACTION',                     @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'SALESTRANSACTION',                     @ModelObjectPart = N'Hub Loader',                           @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'SALESTRANSACTION',                     @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'SALESTRANSACTION',                     @ModelObjectPart = N'Satellite Loader',                     @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'SALESTRANSACTION',                     @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;

GO
