--.........................................................................
--SQL script for post deployment configuration of load control
--Project: Product Launch Event
--Layer: Mart
--.........................................................................
USE [{loadcontrol#loadcontrol#database_name}];
GO


--.........................................................................
--Prepare registration of load objects
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[Build_LoadConfig] @LoadConfig = N'Product Launch Event', @ModelObjectLayer = N'Mart';

--.........................................................................
--Register load objects
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'BRANCH',                               @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Mart',                                 @ModelObjectType = N'Mart Dimension',                       @LoadObject = N'DM_MD_BRANCH_Loader',                  @SchemaName = N'{productlaunchevent#mart#schema_name}', @DatabaseName = N'{productlaunchevent#mart#database_name}', @ServerName = N'{productlaunchevent#mart#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 4070, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Customer_Current',                     @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Mart',                                 @ModelObjectType = N'Mart Dimension',                       @LoadObject = N'DM_MD_Customer_Current_Loader',        @SchemaName = N'{productlaunchevent#mart#schema_name}', @DatabaseName = N'{productlaunchevent#mart#database_name}', @ServerName = N'{productlaunchevent#mart#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 4040, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Customer_History',                     @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Mart',                                 @ModelObjectType = N'Mart Dimension',                       @LoadObject = N'DM_MD_Customer_History_Loader',        @SchemaName = N'{productlaunchevent#mart#schema_name}', @DatabaseName = N'{productlaunchevent#mart#database_name}', @ServerName = N'{productlaunchevent#mart#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 4070, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEM',                                 @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Mart',                                 @ModelObjectType = N'Mart Dimension',                       @LoadObject = N'DM_MD_ITEM_Loader',                    @SchemaName = N'{productlaunchevent#mart#schema_name}', @DatabaseName = N'{productlaunchevent#mart#database_name}', @ServerName = N'{productlaunchevent#mart#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 4070, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEMUNITOFMEASURE',                    @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Mart',                                 @ModelObjectType = N'Mart Dimension',                       @LoadObject = N'DM_MD_ITEMUNITOFMEASURE_Loader',       @SchemaName = N'{productlaunchevent#mart#schema_name}', @DatabaseName = N'{productlaunchevent#mart#database_name}', @ServerName = N'{productlaunchevent#mart#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 4070, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Sales',                                @ModelObjectPart = N'Mart Fact TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Mart',                                 @ModelObjectType = N'Mart Fact',                            @LoadObject = N'DM_MF_Sales_TruncateInsertLoader',     @SchemaName = N'{productlaunchevent#mart#schema_name}', @DatabaseName = N'{productlaunchevent#mart#database_name}', @ServerName = N'{productlaunchevent#mart#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 4120, @ExecutionPriority = 0, @IsActive = 1;

--.........................................................................
--Register load object dependencies
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'BRANCH',                               @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'BRANCH',                               @DependentOnModelObjectPart = N'Satellite Loader',                     @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Customer_Current',                     @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'CUSTOMER',                             @DependentOnModelObjectPart = N'Hub Loader',                           @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Customer_Current',                     @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'CUSTOMER_Address',                     @DependentOnModelObjectPart = N'Satellite Loader',                     @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Customer_Current',                     @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'CUSTOMER_Info',                        @DependentOnModelObjectPart = N'Satellite Loader',                     @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Customer_Current',                     @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'CUSTOMER_PIT',                         @DependentOnModelObjectPart = N'Business PIT Loader',                  @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Customer_History',                     @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'CUSTOMER',                             @DependentOnModelObjectPart = N'Hub Loader',                           @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Customer_History',                     @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'CUSTOMER_Address',                     @DependentOnModelObjectPart = N'Satellite Loader',                     @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Customer_History',                     @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'CUSTOMER_Info',                        @DependentOnModelObjectPart = N'Satellite Loader',                     @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Customer_History',                     @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'CUSTOMER_PIT',                         @DependentOnModelObjectPart = N'Business PIT Loader',                  @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEM',                                 @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'ITEM',                                 @DependentOnModelObjectPart = N'Hub Loader',                           @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEM',                                 @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'ITEM',                                 @DependentOnModelObjectPart = N'Satellite Loader',                     @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEMUNITOFMEASURE',                    @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'ITEMUNITOFMEASURE',                    @DependentOnModelObjectPart = N'Hub Loader',                           @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'ITEMUNITOFMEASURE',                    @ModelObjectPart = N'Mart Dimension Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'ITEMUNITOFMEASURE',                    @DependentOnModelObjectPart = N'Satellite Loader',                     @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Sales',                                @ModelObjectPart = N'Mart Fact TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'BRANCH',                               @DependentOnModelObjectPart = N'Mart Dimension Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Sales',                                @ModelObjectPart = N'Mart Fact TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'Customer_History',                     @DependentOnModelObjectPart = N'Mart Dimension Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Sales',                                @ModelObjectPart = N'Mart Fact TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'ITEM',                                 @DependentOnModelObjectPart = N'Mart Dimension Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Sales',                                @ModelObjectPart = N'Mart Fact TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'ITEMUNITOFMEASURE',                    @DependentOnModelObjectPart = N'Mart Dimension Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Sales',                                @ModelObjectPart = N'Mart Fact TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'Sales',                                @DependentOnModelObjectPart = N'Business Link Loader',                 @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Product Launch Event',                 @ModelObject = N'Sales',                                @ModelObjectPart = N'Mart Fact TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Product Launch Event',                 @DependentOnModelObject = N'SALESTRANSACTION',                     @DependentOnModelObjectPart = N'Satellite Loader',                     @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;

GO
