name: 'Product Launch Event'
description: 'product-launch-event'
id: 'f4af988b-6568-4aee-2bb3-08db50014549'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Mssql'
  version: '1.5.0'
sourceSystems: []
version: 'v1.4'
propertyValues: []
