name: 'Product Launch Event'
description: 'product-launch-event'
id: 'f4af988b-6568-4aee-2bb3-08db50014549'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Mssql'
  version: '1.5.0'
sourceSystems:
  - name: 'POS'
    description: 'POS'
    id: 'a86540c3-707b-4e4a-b19f-2317c01d045b'
    activeDiscovery: '8b609b52-8c82-44b7-9cc1-18bc0fab9762'
version: 'v1.4'
propertyValues: []
