views:
  - id: '2edf46ca-c8ac-45eb-833e-a54ed53c325f'
    name: 'Datamodel View 1'
    type: 'data-model'
    default: true
    description: 'Default view for data model.'
    modelObjects: []
  - id: 'edfe9c89-57e1-4f41-a8c1-d53b6de09472'
    name: 'Sales Information ERP'
    type: 'data-pipe'
    default: true
    description: 'ERP Sales Information'
    modelObjects: []
