views:
  - id: '2edf46ca-c8ac-45eb-833e-a54ed53c325f'
    name: 'Datamodel View 1'
    type: 'data-model'
    default: true
    description: 'Default view for data model.'
    modelObjects: []
  - id: 'edfe9c89-57e1-4f41-a8c1-d53b6de09472'
    name: 'Sales Information ERP'
    type: 'data-pipe'
    default: true
    description: 'ERP Sales Information'
    modelObjects:
      - id: '9f19d8cc-f3a6-43f7-acfd-e1523b39353b'
      - id: 'ee1d26fd-9d08-4099-9bad-a08fb9aa11b5'
      - id: '41aad21e-c17d-4872-975a-adfa315dee13'
  - id: '2142fb6b-b215-4238-b0e5-4bd90041a867'
    name: 'Sales Information POS'
    type: 'data-pipe'
    default: false
    description: 'Sales Information POS'
    modelObjects:
      - id: 'b8472bc6-3141-40cd-9798-187139499292'
      - id: '9f19d8cc-f3a6-43f7-acfd-e1523b39353b'
      - id: 'ee1d26fd-9d08-4099-9bad-a08fb9aa11b5'
      - id: '62c29db0-10a1-4b01-82df-59b9d9914590'
      - id: '13032dc0-dd00-42ab-8392-ef68f1fb90f5'
